services:
  music-disc:
    image: hmes98318/music-disc:latest
    container_name: music-disc
    restart: always
    environment:
      TZ: "Asia/Taipei"
      BOT_TOKEN: "your_token"

      # OAUTH2 mode requires setting BOT_ADMIN, BOT_CLIENT_SECRET value
      BOT_ADMIN: ""
      BOT_CLIENT_SECRET: ""

      BOT_NAME: "Music Disc"
      BOT_PREFIX: "+"
      BOT_PLAYING: "+help | music"
      BOT_EMBEDS_COLOR: "#FFFFFF"
      BOT_SLASH_COMMAND: true

      DEFAULT_VOLUME: 50
      MAX_VOLUME: 100

      AUTO_LEAVE: true
      AUTO_LEAVE_COOLDOWN: 5000
      DISPLAY_VOICE_STATE: true

      # Web dashboard settings
      ENABLE_SITE: true
      SITE_PORT: 33333
      SITE_LOGIN_TYPE: "USER"   # "OAUTH2" | "USER"
      # USER mode settings
      SITE_USERNAME: "admin"
      SITE_PASSWORD: "password"
      # OAUTH2 mode settings
      SITE_OAUTH2_LINK: ""      # Your OAuth2 authentication link
      SITE_OAUTH2_REDIRECT_URI: "http://localhost:33333/login"   # Redirect link after OAuth2 authentication is complete

      # Local Lavalink node
      ENABLE_LOCAL_NODE: false
      LOCAL_NODE_AUTO_RESTART: true
    volumes:
      - ./logs:/bot/logs                        # Bot logs
      - ./server:/bot/server                    # localnode configuration file
      - ./nodelist.json:/bot/nodelist.json      # Lavalink node list
      - ./blacklist.json:/bot/blacklist.json    # Discord user blacklist
    ports:
      - 33333:33333
